# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkServiceInterface' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkInterface

  target 'NetworkServiceInterfaceTests' do
    # Pods for testing
  end

  pod 'NetworkService', :path => '../service/NetworkService'

end
