# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LocalStorageService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LocalStorageService

  target 'LocalStorageServiceTests' do
    # Pods for testing
  end

end
