# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'DesignSystemDevApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'DesignSystem', path: '../../DesignSystem'
  # Pods for DesignSystem

end
